"""Canonical batch contract — vocabulary, normalization and AutoBatch planner.

This module is the single source of truth for the *canonical batch contract*
(mission ``zsss-winsorized-gpu-perf-memory``, Phase B1).  It is pure stdlib:
no Qt, no Tk, no numpy, no engine imports — so every GUI shell, the queue
manager and the tests share one exact vocabulary and cannot drift.

Canonical values
----------------
* ``BATCH_AUTO == 0``   : Auto.  ZSSS resolves a concrete ``B_resolved`` once,
  before scientific batch execution, then freezes it for the run/resume
  contract.  ``0`` is the single canonical Auto value: ``-1`` is a legacy
  Auto spelling that must be normalized to ``0`` at the compatibility
  boundary and MUST NOT be generated by new code.
* ``BATCH_BORING == 1`` : Boring (per-frame live / single-image streaming).
* ``batch_size >= 2``   : explicit scientific batch capacity.

Terms
-----
* ``B_requested`` : what the user asked (``0`` Auto / ``1`` Boring / ``>= 2``
  explicit).  Never mutated after the run request is captured.
* ``B_resolved``  : the capacity frozen for the run.  ``>= 1`` always.  Chosen
  ONCE before scientific batch execution; nothing may shrink it afterwards
  (no timing/CPU/GPU/RAM-driven dynamic mutation).  Persisted so a Resume
  reuses the exact frozen value instead of re-estimating from current RAM.
* ``N_batch``     : the actual current reduction population of one batch,
  always ``1 <= N_batch <= B_resolved``.  The final partial batch
  (``N_batch < B_resolved``) is natural, never a mutation.  All Winsor-rank
  reasoning must use ``N_batch`` (the live population), never blindly
  ``B_resolved``.

Reproject&Coadd is an independent execution-mode concept carried by its own
flags (``reproject_coadd_final`` / final-combine token) and MUST NOT depend on
the Auto sentinel ``0``.

AutoBatch planner
-----------------
``AutoBatchPlanner`` is an independently-testable planner whose inputs are
injectable (available RAM, image dims, queue length, safety reserve, memory
query).  It is backend-independent: CPU Auto and GPU Auto resolve the same
``B_resolved`` for identical workload/host-memory inputs; the GPU backend
never participates in choosing a *smaller scientific* value.  When memory
discovery fails the planner falls back conservatively (never guesses huge),
and for a static finite queue ``B_resolved`` never exceeds the number of
available scientific input samples when that count is known.
"""

from __future__ import annotations

from typing import Callable, Optional, Sequence, Tuple

# Canonical batch values -----------------------------------------------------
BATCH_AUTO = 0
BATCH_BORING = 1

# Planner parameter defaults (legacy-compatible where an engine wrapper relies
# on the historical ``estimate_batch_size`` numeric behavior).
DEFAULT_MEMORY_FACTOR = 6.0          # alignment + stacking buffers per image
DEFAULT_SAFETY_FACTOR = 1.5          # system usage / python overhead
DEFAULT_CHANNELS = 3                 # worst-case color output
DEFAULT_BYTES_PER_FLOAT = 4
DEFAULT_FALLBACK_IMAGE_HW = (2000, 2000)
DEFAULT_MAX_BATCH = 50
DEFAULT_MIN_BATCH = 1
DEFAULT_FALLBACK_BATCH = 10

# Mode vocabulary ------------------------------------------------------------
BATCH_MODE_AUTO = "auto"
BATCH_MODE_BORING = "boring"
BATCH_MODE_EXPLICIT = "explicit"


def normalize_batch_requested(value) -> int:
    """Return the canonical requested batch value for ``value``.

    Compatibility-boundary normalizer:

    * any negative value (including the legacy Auto sentinel ``-1``) -> ``0``
      (canonical Auto).  New code must never generate ``-1``; the engine may
      only *recognize* legacy negatives here and normalize them.
    * ``0``                      -> ``0`` (canonical Auto, unchanged).
    * ``1``                      -> ``1`` (Boring).
    * ``>= 2``                   -> the explicit integer capacity.
    * non-integer garbage        -> ``0`` (Auto) — fail-safe toward the
      documented default rather than inventing an unexplained batch value.
    """
    try:
        requested = int(value)
    except (TypeError, ValueError):
        return BATCH_AUTO
    if requested < BATCH_AUTO:
        return BATCH_AUTO
    return requested


def batch_requested_mode(value) -> str:
    """Classify a canonical requested batch value into a mode token."""
    requested = normalize_batch_requested(value)
    if requested == BATCH_AUTO:
        return BATCH_MODE_AUTO
    if requested == BATCH_BORING:
        return BATCH_MODE_BORING
    return BATCH_MODE_EXPLICIT


def is_auto(value) -> bool:
    """True when ``value`` requests Auto batching (canonical ``0``)."""
    return normalize_batch_requested(value) == BATCH_AUTO


def is_boring(value) -> bool:
    """True when ``value`` requests the Boring single-image path (``1``)."""
    return normalize_batch_requested(value) == BATCH_BORING


def clamp_resolved_to_samples(resolved: int, n_samples: Optional[int]) -> int:
    """Cap a resolved batch capacity to a known static sample count.

    ``n_samples`` may be ``None`` (unknown — no cap) or a non-negative count.
    Returns at least ``1`` when samples are known to exist; a known empty
    queue cannot yield a positive capacity above its (zero) population.
    """
    try:
        resolved = max(1, int(resolved))
    except (TypeError, ValueError):
        resolved = DEFAULT_MIN_BATCH
    if n_samples is None:
        return resolved
    try:
        samples = max(0, int(n_samples))
    except (TypeError, ValueError):
        return resolved
    if samples <= 0:
        return 1
    return min(resolved, samples)


def single_image_estimate_bytes(
    image_hw: Optional[Tuple[int, int]] = None,
    channels: int = DEFAULT_CHANNELS,
    bytes_per_float: int = DEFAULT_BYTES_PER_FLOAT,
    memory_factor: float = DEFAULT_MEMORY_FACTOR,
) -> int:
    """Conservative per-image processing footprint estimate (bytes).

    ``image_hw`` is ``(H, W)``.  When unknown (or degenerate) the
    conservative fallback footprint of a ~4 MP color image is returned, so a
    failed image probe can never produce an over-aggressive (larger) batch.
    """
    if image_hw is None:
        h, w = DEFAULT_FALLBACK_IMAGE_HW
    else:
        try:
            h, w = int(image_hw[0]), int(image_hw[1])
        except (TypeError, ValueError, IndexError):
            h, w = DEFAULT_FALLBACK_IMAGE_HW
    h = max(1, h)
    w = max(1, w)
    channels = max(1, int(channels))
    bytes_per_float = max(1, int(bytes_per_float))
    memory_factor = float(memory_factor) if memory_factor and memory_factor > 0 else DEFAULT_MEMORY_FACTOR
    return int(h * w * channels * bytes_per_float * memory_factor)


def plan_auto_batch(
    available_ram_bytes: Optional[int] = None,
    *,
    image_hw: Optional[Tuple[int, int]] = None,
    queue_length: Optional[int] = None,
    channels: int = DEFAULT_CHANNELS,
    bytes_per_float: int = DEFAULT_BYTES_PER_FLOAT,
    memory_factor: float = DEFAULT_MEMORY_FACTOR,
    safety_factor: float = DEFAULT_SAFETY_FACTOR,
    reserve_bytes: Optional[int] = None,
    min_batch: int = DEFAULT_MIN_BATCH,
    max_batch: int = DEFAULT_MAX_BATCH,
    fallback_batch: int = DEFAULT_FALLBACK_BATCH,
    usable_memory_fraction: Optional[float] = None,
    memory_provider: Optional[Callable[[], int]] = None,
    memory_query: Optional[Callable[[], int]] = None,
) -> int:
    """Resolve one Auto batch capacity from injectable inputs.

    Pure planner kernel — no I/O, no psutil import, backend-independent.

    Parameters
    ----------
    available_ram_bytes:
        Available host RAM in bytes.  When omitted, ``memory_provider`` /
        ``memory_query`` (aliases, both ``() -> int``) are consulted; when no
        provider is available or the query fails/returns a non-positive
        value, the conservative ``fallback_batch`` is returned (never a huge
        guess, never a crash).
    image_hw:
        ``(H, W)`` of one scientific input sample (``None`` -> conservative
        ~4 MP fallback footprint).
    queue_length:
        Known static sample count.  When provided, the resolved capacity is
        capped so ``B_resolved <= samples``.
    usable_memory_fraction:
        Fraction of available RAM usable by stacking (0..1).  ``None`` keeps
        the legacy 70% policy.
    reserve_bytes:
        Explicit safety reserve in bytes (``None`` -> legacy 70% usable
        fraction times the safety factor is applied on top of the image
        footprint, i.e. ``usable / (per_image * safety_factor)``).
    min_batch / max_batch:
        Clamp window for the resolved capacity (``min_batch >= 1``).
    fallback_batch:
        Conservative value returned when memory discovery fails.
    """
    try:
        min_batch = max(1, int(min_batch))
    except (TypeError, ValueError):
        min_batch = DEFAULT_MIN_BATCH
    try:
        max_batch = max(min_batch, int(max_batch))
    except (TypeError, ValueError):
        max_batch = DEFAULT_MAX_BATCH
    try:
        fallback_batch = max(1, int(fallback_batch))
    except (TypeError, ValueError):
        fallback_batch = DEFAULT_FALLBACK_BATCH

    available = available_ram_bytes
    if available is None or available <= 0:
        for provider in (memory_provider, memory_query):
            if provider is None:
                continue
            try:
                probed = int(provider())
            except Exception:
                probed = 0
            if probed and probed > 0:
                available = probed
                break
    if available is None or available <= 0:
        # Memory discovery failed: conservative fallback.  Never infer RAM
        # from hardware names; never let a failed probe grow the batch.
        return min(fallback_batch, max_batch)

    if usable_memory_fraction is None:
        usable_memory_fraction = 70.0 / 100.0
    try:
        fraction = float(usable_memory_fraction)
    except (TypeError, ValueError):
        fraction = 0.70
    if not 0.0 < fraction <= 1.0:
        fraction = 0.70
    usable = float(available) * fraction
    if reserve_bytes is not None:
        try:
            usable = max(0.0, usable - float(reserve_bytes))
        except (TypeError, ValueError):
            pass

    per_image = single_image_estimate_bytes(
        image_hw=image_hw,
        channels=channels,
        bytes_per_float=bytes_per_float,
        memory_factor=memory_factor,
    )
    try:
        safety = float(safety_factor) if safety_factor and safety_factor > 0 else DEFAULT_SAFETY_FACTOR
    except (TypeError, ValueError):
        safety = DEFAULT_SAFETY_FACTOR
    divisor = float(per_image) * safety
    if divisor <= 0 or usable <= 0:
        return min_batch

    estimated = int(usable / divisor)
    estimated = max(min_batch, min(max_batch, estimated))

    # Static finite queue: never resolve above the available scientific
    # sample count when that count is known and meaningful.
    if queue_length is not None:
        try:
            samples = max(0, int(queue_length))
        except (TypeError, ValueError):
            samples = 0
        if samples > 0:
            estimated = min(estimated, samples)
    return max(min_batch, estimated)


class AutoBatchPlanner:
    """Independently-testable AutoBatch planner (injectable inputs).

    Example
    -------
    >>> planner = AutoBatchPlanner(available_ram_bytes=8 << 30, image_hw=(1920, 1080))
    >>> planner.resolve(queue_length=24)
    12

    All inputs are injectable at construction and/or per call; nothing in the
    planner performs process-wide memory discovery itself, so unit tests can
    drive very-low / moderate / large RAM, memory-query failures, tiny
    images, RGB sensors and finite queues without touching the real host.
    """

    def __init__(
        self,
        available_ram_bytes: Optional[int] = None,
        *,
        memory_provider: Optional[Callable[[], int]] = None,
        memory_query: Optional[Callable[[], int]] = None,
        image_hw: Optional[Tuple[int, int]] = None,
        channels: int = DEFAULT_CHANNELS,
        bytes_per_float: int = DEFAULT_BYTES_PER_FLOAT,
        memory_factor: float = DEFAULT_MEMORY_FACTOR,
        safety_factor: float = DEFAULT_SAFETY_FACTOR,
        reserve_bytes: Optional[int] = None,
        min_batch: int = DEFAULT_MIN_BATCH,
        max_batch: int = DEFAULT_MAX_BATCH,
        fallback_batch: int = DEFAULT_FALLBACK_BATCH,
        usable_memory_fraction: Optional[float] = None,
    ) -> None:
        self.available_ram_bytes = available_ram_bytes
        self.memory_provider = memory_provider
        self.memory_query = memory_query
        self.image_hw = image_hw
        self.channels = channels
        self.bytes_per_float = bytes_per_float
        self.memory_factor = memory_factor
        self.safety_factor = safety_factor
        self.reserve_bytes = reserve_bytes
        self.min_batch = min_batch
        self.max_batch = max_batch
        self.fallback_batch = fallback_batch
        self.usable_memory_fraction = usable_memory_fraction

    def resolve(self, queue_length: Optional[int] = None) -> int:
        """Return one frozen Auto capacity for the configured workload."""
        return plan_auto_batch(
            self.available_ram_bytes,
            image_hw=self.image_hw,
            queue_length=queue_length,
            channels=self.channels,
            bytes_per_float=self.bytes_per_float,
            memory_factor=self.memory_factor,
            safety_factor=self.safety_factor,
            reserve_bytes=self.reserve_bytes,
            min_batch=self.min_batch,
            max_batch=self.max_batch,
            fallback_batch=self.fallback_batch,
            usable_memory_fraction=self.usable_memory_fraction,
            memory_provider=self.memory_provider,
            memory_query=self.memory_query,
        )

    def resolve_from_samples(self, samples: Sequence) -> int:
        """Resolve with ``queue_length`` bound to a known static sample list."""
        try:
            length = len(samples)
        except (TypeError, ValueError):
            length = None
        return self.resolve(queue_length=length)
