"""
English translation file for Seestar Stacker.
"""

EN_TRANSLATIONS = {
    # Main interface & Common
    "title": "Seestar Stacker",
    "error": "Error",
    "warning": "Warning",
    "info": "Information",
    "quit": "Quit",
    "browse": "Browse",  # Generic key
    "browse_input_button": "Browse...",  # Unique key for button
    "browse_output_button": "Browse...",  # Unique key for button
    "browse_ref_button": "Browse...",  # Unique key for button
    "drizzle_options_frame_label": "Drizzle Options",
    "drizzle_activate_check": "Enable Drizzle (experimental, slow)",
    "drizzle_scale_label": "Scale Factor:",
    "drizzle_radio_2x_label": "x2",
    "drizzle_radio_3x_label": "x3",
    "drizzle_radio_4x_label": "x4",
    "drizzle_mode_label": "Drizzle Mode:",
    "drizzle_radio_final": "Standard (Final)",
    "drizzle_radio_incremental": "Incremental (Disk Saving)",
    "drizzle_kernel_label": "Kernel:",
    "drizzle_pixfrac_label": "Pixfrac:",
    "drizzle_wht_threshold_label": "WHT Threshold%:",
    # --- Control Tabs ---
    "tab_stacking": "Stacking",
    "tab_preview": "Preview",
    # --- Stacking Tab ---
    "Folders": "Folders",
    "input_folder": "Input:",
    "output_folder": "Output:",
    "output_filename_label": "Filename:",
    "reference_image": "Reference :",
    "last_stack_treated": "Last stack :",
    "options": "Stacking Options",
    "stacking_method": "Method:",
    "kappa_value": "Kappa:",
    "batch_size": "Batch Size:",
    "batch_size_auto": "(0=auto)",  # Gardé même si 0 n'est plus auto pour compatibilité affichage
    "hot_pixels_correction": "Hot Pixel Correction",
    "perform_hot_pixels_correction": "Correct hot pixels",
    "hot_pixel_threshold": "Threshold:",
    "neighborhood_size": "Neighborhood:",
    "post_proc_opts_frame_label": "Post-Processing Options",
    "cleanup_temp_check_label": "Cleanup temporary files after processing",
    "stacking_norm_method_label": "Normalization:",
    "norm_method_none": "None",
    "norm_method_linear_fit": "Linear Fit (Sky)",
    "norm_method_sky_mean": "Sky Mean Subtraction",
    "stacking_weight_method_label": "Weighting:",
    "weight_method_none": "None",
    "weight_method_noise_variance": "Noise Variance (1/σ²)",
    "weight_method_noise_fwhm": "Noise + FWHM",
    "weight_method_quality": "Quality (SNR & Stars)",
    "reject_algo_kappa_sigma": "Kappa-Sigma Clip",
    "reject_algo_winsorized_sigma_clip": "Winsorized Sigma Clip",
    "reject_algo_linear_fit_clip": "Linear Fit Clip",
    "stacking_kappa_low_label": "Kappa Low:",
    "stacking_kappa_high_label": "Kappa High:",
    "stacking_winsor_limits_label": "Winsor Limits (low,high):",
    "stacking_winsor_note": "(e.g., 0.05,0.05 for 5% each side)",
    "stacking_final_combine_label": "Final Combine:",
    "hq_ram_limit_label": "HQ RAM limit (GB)",
    "combine_method_mean": "Mean",
    "combine_method_median": "Median",
    "combine_method_winsorized_sigma_clip": "Winsorized Sigma Clip",
    "combine_method_reproject": "Reproject",
    "stack_method_label": "Method:",
    "method_mean": "Mean",
    "method_median": "Median",
    "method_kappa_sigma": "Kappa-Sigma Clip",
    "method_winsorized_sigma_clip": "Winsorized Sigma Clip",
    "method_linear_fit_clip": "Linear Fit Clip",
    "kappa_sigma": "Kappa-Sigma Clip",
    "winsorized_sigma_clip": "Winsorized Sigma Clip",
    "linear_fit_clip": "Linear Fit Clip",
    "linear_fit": "Linear Fit (Sky)",
    "noise_variance": "Noise Variance (1/σ²)",
    # SCNR Translations ###
    "apply_final_scnr_label": "Apply Final SCNR (Green)",
    "final_scnr_amount_label": "SCNR Amount:",
    "final_scnr_preserve_lum_label": "Preserve Luminosity (SCNR)",
    ### Expert Tab Translations ###
    "tab_expert_title": "Expert",
    "expert_warning_text": "Abandon all hope, ye who enter here! (Advanced Settings)",
    # Auto Background Neutralization (BN) Section
    "bn_frame_title": "Auto Background Neutralization (BN)",
    "bn_grid_size_label": "BN Grid Size:",
    "bn_perc_low_label": "BG Perc. Low:",
    "bn_perc_high_label": "BG Perc. High:",
    "bn_std_factor_label": "BG Std Factor:",
    "bn_min_gain_label": "BN Min Gain:",
    "bn_max_gain_label": "BN Max Gain:",
    # ChromaticBalancer (CB) / Edge Enhance Section
    "cb_frame_title": "Edge/Chroma Correction (CB)",
    "cb_border_size_label": "CB Border Size (px):",
    "cb_blur_radius_label": "CB Blur Radius (px):",
    "cb_min_b_factor_label": "CB Min Blue Factor:",  # Assuming exposing Blue factor
    "cb_max_b_factor_label": "CB Max Blue Factor:",  # and potentially R too
    # 'cb_intensity_label': "Edge Correction Intensity:", # If you add this slider
    # Final Cropping Section
    "crop_frame_title": "Final Cropping",
    "final_edge_crop_label": "Edge Crop (%):",
    # Reset Expert Button
    "reset_expert_button": "Reset Expert Settings",
    ### Translations for Photutils Background Subtraction (Expert Tab) ###
    "photutils_bn_frame_title": "2D Background Subtraction (Photutils)",
    "apply_photutils_bn_label": "Enable Photutils 2D Background Subtraction",
    "photutils_bn_box_size_label": "Box Size (px):",
    "photutils_bn_filter_size_label": "Filter Size (px, odd):",
    "photutils_bn_sigma_clip_label": "Sigma Clip:",
    "photutils_bn_exclude_percentile_label": "Exclude Brightest (%):",
    ### END expert tab ###
    # --- Output Format Section ---
    "output_format_frame_title": "Output FITS Format",
    "save_as_float32_label": "Save final FITS as float32 (larger files, max precision)",
    "preserve_linear_output_label": "Preserve linear output (skip percentile scaling)",
    ### NEW: Tooltips for Expert Tab ###
    "tooltip_bn_grid_size": "BN: RxC grid for background analysis. More zones (32x32) = finer local analysis, noise sensitive. Fewer (8x8) = robust stats, worse for complex gradients. Default: 16x16.",
    "tooltip_bn_perc_low": "BN: Lower percentile for background zone luminance. Zones with median luminance BELOW this overall percentile are less considered pure background. Range: 0-40. Default: 5.",
    "tooltip_bn_perc_high": "BN: Upper percentile for background zone luminance. Zones with median luminance ABOVE this are excluded from background. Range: (PercLow+1)-95. Default: 30.",
    "tooltip_bn_std_factor": "BN: Factor for standard deviation. Background zones if their std_dev < (median_std_of_all_zones * factor). Lower = stricter. Higher = looser (riskier). Range: 0.5-5. Default: 1.0.",
    "tooltip_bn_min_gain": "BN: Minimum gain applied to R/B channels to match G. Limits correction. Range: 0.1-2. Default: 0.2.",
    "tooltip_bn_max_gain": "BN: Maximum gain applied to R/B channels. Limits correction. Range: 1-10. Default: 7.0.",
    "tooltip_cb_border_size": "Edge Correct: Width (px) of border region analyzed for local color shifts. Smaller = targets finer fringes. Larger = broader correction. Range: 5-150. Default: 25.",
    "tooltip_cb_blur_radius": "Edge Correct: Radius (px) to blur the edge mask. Softens correction transition. Smaller = sharper transition. Range: 0-50. Default: 8.",
    "tooltip_cb_min_b_factor": "Edge Correct: Minimum gain factor applied to Blue channel in border regions to match local G. Limits reduction. Range: 0.1-1.0. Default: 0.4.",
    "tooltip_cb_max_b_factor": "Edge Correct: Maximum gain factor applied to Blue channel. Limits amplification. Range: 1.0-3.0. Default: 1.5.",
    "tooltip_final_edge_crop_percent": "Final Crop: Percentage of image to crop from EACH side (L,R,T,B) before final save. Ex: 2.0 for 2%. Range: 0-25. Default: 2.0.",
    "tooltip_apply_final_scnr": "SCNR: Applies Subtle Color Noise Reduction to the final stack, targeting Green by default to reduce green/magenta casts.",
    "tooltip_final_scnr_amount": "SCNR Amount: Strength of Green reduction (0.0=none, 1.0=full replacement by R/B reference). Typical: 0.6-0.9. Default: 0.8.",
    "tooltip_final_scnr_preserve_lum": "SCNR Preserve Luminosity: If checked, attempts to restore original pixel luminance after color correction, preventing excessive darkening.",
    "tooltip_apply_feathering": "Feathering: If enabled, smooths the stacked image based on a blurred version of the total weight map. Can help reduce sharp transitions or artifacts at combined data edges or where weights change abruptly. Acts before Photutils background subtraction.",
    "tooltip_feather_blur_px": "Feather Blur Radius (px): Controls the extent of blur applied to the weight map for feathering. Larger values result in smoother, more gradual transitions. Typical range: 64-512. Default: 256.",
    # Tooltips for Photutils BN
    "tooltip_apply_photutils_bn": "PB2D: Enables subtraction of a 2D background model computed by Photutils. Acts before global Background Neutralization. Useful for complex gradients.",
    "tooltip_photutils_bn_box_size": "PB2D: Size of the boxes (px) for local background estimation. Should be large enough to avoid stars, but small enough to follow the gradient. Default: 128.",
    "tooltip_photutils_bn_filter_size": "PB2D: Size of the median filter (px, odd) applied to the map of local background estimates to smooth it. Default: 5.",
    "tooltip_photutils_bn_sigma_clip": "PB2D: Sigma value for iterative pixel rejection (stars) within each box during background estimation. Default: 3.0.",
    "tooltip_photutils_bn_exclude_percentile": "PB2D: Percentage (0-100) of the brightest pixels to ignore within each box before background estimation. Helps reject stars without a full mask. Default: 98.0.",
    # Tooltips for Low WHT Mask
    "tooltip_apply_low_wht_mask": "Low WHT Mask: Attenuates image areas where the weight map (WHT) is very low (typically edges with little signal). Helps reduce banding and color casts in these zones. Applied after Feathering and before Photutils background subtraction.",
    "tooltip_low_wht_percentile": "Low WHT Percentile: Defines the threshold for considering a weight as 'low'. E.g., 5% means the bottom 5% of non-zero pixel weights will be targeted. Range: 1-20. Default: 5.",
    "tooltip_low_wht_soften_px": "Soften Low WHT Mask (px): Radius of Gaussian blur applied to the binary mask of low-weight areas. Allows for a smoother transition of the correction. Range: 32-512. Default: 128.",
    # Tooltips save_as_float32
    "tooltip_save_as_float32": "If checked, the final FITS file will be saved using 32-bit floating-point numbers, preserving the maximum numerical precision from processing but resulting in larger files (approx. 2x). If unchecked (default), the file will be saved as 16-bit unsigned integers (0-65535 range after scaling from 0-1), significantly reducing file size.",
    "tooltip_preserve_linear_output": "If enabled, skips percentile-based normalization before saving. The uint16 output will scale the raw 0-1 values directly to 0-65535.",
    # ... end expert tab ...
    # --- Preview Tab ---
    "white_balance": "White Balance (Preview)",
    "wb_r": "R Gain:",
    "wb_g": "G Gain:",
    "wb_b": "B Gain:",
    "auto_wb": "Auto WB",
    "reset_wb": "Reset WB",
    "stretch_options": "Stretch (Preview)",
    "stretch_method": "Method:",
    "stretch_bp": "Black:",
    "stretch_wp": "White:",
    "stretch_gamma": "Gamma:",
    "auto_stretch": "Auto Stretch",
    "reset_stretch": "Reset Stretch",
    "image_adjustments": "Image Adjustments",
    "brightness": "Brightness:",
    "contrast": "Contrast:",
    "saturation": "Saturation:",
    "reset_bcs": "Reset Adjust.",
    # --- Progress Area ---
    "progress": "Progress",
    "estimated_time": "ETA:",
    "elapsed_time": "Elapsed:",
    "Remaining:": "Remaining:",  # Key for static label
    "Additional:": "Additional:",  # Key for static label
    "aligned_files_label": "Aligned:",  # Static label text (placeholder)
    "aligned_files_label_format": "Aligned: {count}",  # Format string for display
    "global_eta_label": "Global ETA:",  # Global ETA label
    # --- Preview Area (Right Panel) ---
    "preview": "Preview",
    "histogram": "Histogram",
    "zoom_histo_button": "Zoom Histogram",
    "reset_histo_button": "Reset Histogram",
    "auto_zoom_histo_check": "Auto zoom histogram",
    # --- Control Buttons ---
    "start": "Start",
    "stop": "Stop",
    "add_folder_button": "Add Folder",
    "copy_log_button_text": "Copy",
    "open_output_button_text": "Open Output",
    "show_folders_button_text": "View Inputs",
    "analyze_folder_button": "Analyze Input Folder",  # <-- NOUVELLE LIGNE AJOUTÉE ICI
    # --- Dialog Titles ---
    "Select Input Folder": "Select Input Folder",
    "Select Output Folder": "Select Output Folder",
    "Select Reference Image (Optional)": "Select Reference Image (Optional)",
    "Select Additional Images Folder": "Select Folder with Additional Images",
    "input_folders_title": "Input Folder List",
    "no_input_folder_set": "No input folder has been selected yet.",
    # --- Status Messages & Errors ---
    "select_folders": "Please select input and output folders.",
    "input_folder_invalid": "Invalid input folder",
    "output_folder_invalid": "Invalid output folder/cannot create",
    "Output folder created": "Output folder created",
    "no_fits_found": "No .fit/.fits files found in input folder. Start anyway?",
    "Error reading input folder": "Error reading input folder",
    "stacking_start": "⚙️ Starting processing...",
    "stacking_stopping": "⚠️ Stopping...",
    "stacking_finished": "🏁 Processing Finished",
    "stacking_error_msg": "Processing Error:",
    "stacking_complete_msg": "Processing complete! Final stack:",
    "stop_requested": "⚠️ Stop requested, finishing current step...",
    "processing_stopped": "🛑 Processing stopped by user.",
    "no_stacks_created": "⚠️ No stacks were created.",
    "Failed to start processing.": "Failed to start processing.",
    "image_info_waiting": "Image info: waiting...",
    "no_files_waiting": "No files waiting",
    "no_additional_folders": "None",
    "1 additional folder": "1 add. folder",
    "{count} additional folders": "{count} add. folders",
    "Start processing to add folders": "Processing must be started to add additional folders.",
    "Processing not active or finished.": "Processing not active or finished.",
    "Folder not found": "Folder not found",
    "Input folder cannot be added": "The main input folder cannot be added.",
    "Output folder cannot be added": "The output folder cannot be added.",
    "Cannot add subfolder of output folder": "Cannot add a subfolder of the output folder.",
    "Folder already added": "This folder is already in the list.",
    "Folder contains no FITS": "Folder contains no FITS files.",
    "Error reading folder": "Error reading folder",
    "Folder added": "Folder added",
    "Folder not added (already present, empty, or error)": "Folder not added (already present, empty, or error)",
    "quit_while_processing": "Processing is active. Quit anyway?",
    "Error during debayering": "Error during debayering",
    "Invalid or missing BAYERPAT": "Invalid or missing BAYERPAT",
    "Treating as grayscale": "Treating as grayscale",
    "Error loading preview image": "Error loading preview image",
    "Error loading preview (invalid format?)": "Error loading preview (invalid format?)",
    "Error loading final stack preview": "Error loading final stack preview",
    "Error loading final preview": "Error loading final preview",
    "No Image Data": "No Image Data",
    "Preview Error": "Preview Error",
    "Preview Processing Error": "Preview Processing Error",
    "Welcome!": "Welcome!",
    "Select input/output folders.": "Select input/output folders.",
    "Auto WB requires a color image preview.": "Auto WB requires a color image preview.",
    "Error during Auto WB": "Error during Auto WB",
    "Auto Stretch requires an image preview.": "Auto Stretch requires an image preview.",
    "Error during Auto Stretch": "Error during Auto Stretch",
    "Total Exp (s)": "Total Exp (s)",
    "processing_report_title": "Processing Summary",
    "report_images_stacked": "Images Stacked:",
    "report_total_exposure": "Total Exposure:",
    "report_total_time": "Total Processing Time:",
    "report_seconds": "seconds",
    "report_minutes": "minutes",
    "report_hours": "hours",
    "eta_calculating": "Calculating...",
    "Weighting": "Weighting",
    "W. Metrics": "W. Metrics",
    "weighting_enabled": "Enabled",
    "weighting_disabled": "Disabled",
    "drizzle_warning_title": "Drizzle Warning",
    "drizzle_warning_text": (
        "Drizzle processing is enabled.\n\n"
        "- This is experimental and may be slow.\n"
        "- It will create temporary files that can consume significant disk space (potentially similar to the input image size).\n"
        "- The live preview will show a standard stack; Drizzle will be applied at the very end.\n\n"
        "Continue with Drizzle?"
    ),
    # --- Analyzer Launch ---
    "analyzer_launch_error_title": "Analyzer Launch Error",
    "analyzer_script_not_found": "Analyzer script not found at:\n{path}\nPlease check the installation.",
    "analyzer_launch_failed": "Failed to launch the analyzer script:\n{error}",
    "analyzer_launched": "Folder analyzer launched.",
    # --- Mosaic Settings ---
    "Mosaic...": "Mosaic...",
    "mosaic_settings_title": "Mosaic Options",
    "mosaic_activation_frame": "Activation",
    "mosaic_activate_label": "Enable Mosaic Processing Mode",
    "cancel": "Cancel",
    "ok": "OK",
    "mosaic_window_create_error": "Could not open Mosaic settings window.",
    "mosaic_mode_enabled_log": "Mosaic mode ENABLED.",
    "mosaic_mode_disabled_log": "Mosaic mode DISABLED.",
    "mosaic_drizzle_options_frame": "Mosaic Drizzle Options",
    "mosaic_drizzle_kernel_label": "Kernel:",
    "mosaic_drizzle_pixfrac_label": "Pixfrac:",
    "mosaic_invalid_kernel": "Invalid Drizzle kernel selected.",
    "mosaic_invalid_pixfrac": "Invalid Pixfrac value. Must be between 0.01 and 1.0.",
    "mosaic_api_key_frame": "Astrometry.net API Key (Required for Mosaic)",
    "mosaic_api_key_label": "API Key:",
    "mosaic_api_key_help": "Get your key from nova.astrometry.net (free account)",
    "mosaic_api_key_required": "Astrometry.net API Key is required when Mosaic Mode is enabled.",
    "mosaic_alignment_method_frame_title": "Mosaic Alignment Method",
    "mosaic_align_local_fast_fallback_label": "Fast Local + WCS Fallback (Recommended)",
    "mosaic_align_local_fast_only_label": "Fast Local Only (Strict)",
    "mosaic_align_astrometry_per_panel_label": "Astrometry.net per Panel (Slower)",
    "fastaligner_tuning_frame_title": "FastAligner Tuning (for Local Alignment)",
    "fa_orb_features_label": "ORB Features:",  # Garder court pour UI
    "fa_min_abs_matches_label": "Min Abs. Matches:",  # Garder court
    "fa_min_ransac_inliers_label": "Min RANSAC Inliers:",  # Garder court
    "fa_ransac_thresh_label": "RANSAC Thresh (px):",  # Garder court
    "mosaic_drizzle_fillval_label": "Fill Value:",  # Nouveau
    "mosaic_drizzle_wht_thresh_label": "Low WHT Mask (%):",  # Nouveau (différent du Drizzle global pour être sûr)
    "mosaic_validation_orb_range": "ORB Features must be between {min_orb} and {max_orb}.",
    "mosaic_validation_matches_range": "Min Absolute Matches must be between {min_matches} and {max_matches}.",
    "mosaic_validation_inliers_range": "Min RANSAC Inliers must be between {min_inliers} and {max_inliers}.",
    "mosaic_validation_ransac_thresh_range": "RANSAC Threshold must be between {min_thresh:.1f} and {max_thresh:.1f}.",
    "mosaic_error_reading_spinbox": "Error reading Spinbox value: {error_details}",
    "mosaic_error_converting_spinbox": "Error converting Spinbox value: {error_details}",
    # --- LocalSolverSettingsWindow ---
    "local_solver_button_text": "Solver Config",
    "local_solver_window_create_error": "Could not open Local Solvers settings window.",
    "local_solver_general_options_frame": "General Local Solver Options",
    "local_solver_use_priority_label": "Prioritize local solvers over Astrometry.net (if paths are set)",
    "local_solver_astap_frame_title": "ASTAP Configuration",
    "local_solver_astap_path_label": "ASTAP Executable Path:",
    "local_solver_astap_data_label": "ASTAP Star Index Data Directory:",
    "local_solver_ansvr_frame_title": "Local Astrometry.net (ansvr) Configuration",
    "local_solver_ansvr_path_label": "Ansvr Config/Data Path:",
    "local_solver_info_text": "Leave paths empty if the solver is not used or is in system PATH.\nConsult solver documentation for specific path requirements.",
    "executable_files": "Executable Files",
    "astap_executable_win": "ASTAP Executable",  # Specific for Windows .exe
    "all_files": "All Files",
    "select_astap_executable_title": "Select ASTAP Executable",
    "select_astap_data_dir_title": "Select ASTAP Star Index Data Directory",
    "select_local_ansvr_path_title": "Select Local Astrometry.net (ansvr) Path",
    "astap_search_radius_label": "ASTAP Search Radius (deg):",
    "local_solver_astap_downsample_label": "ASTAP Downsample (-z):",
    "local_solver_astap_sens_label": "ASTAP Sensitivity (-sens):",
    "tooltip_astap_search_radius": "ASTAP search radius around FITS header RA/DEC. Smaller values are faster if coordinates are good. Recommended: 0.5 to 10 degrees. (0.1-90.0 allowed).",
    "invalid_astap_radius_range": "ASTAP Search Radius must be between 0.1 and 90.0 degrees.",
    "invalid_astap_radius_value": "Invalid value for ASTAP Search Radius. Please enter a number.",
    "settings_save_failed_on_ok": "Settings were updated in memory, but failed to save to file from this window. They will be saved when the main application closes if not overwritten.",
    # --- New Local Solver GUI strings ---
    "solver_config_title": "Local Astrometry Solvers Configuration",
    "use_third_party_solver_label": "Use third-party solver",
    "solver_label": "Solver",
    "solver_astap": "ASTAP",
    "solver_astrometry": "Astrometry.net",
    "solver_ansvr": "Ansvr",
    "astap_exe_label": "Executable:",
    "astap_data_label": "Data Dir:",
    "astrometry_api_key_label": "API Key:",
    "astrometry_dir_label": "solve-field Dir:",
    "ansvr_hostport_label": "Host:Port:",
    "enable_batch_reproject": "Enable inter-batch reprojection (requires WCS)",
    "ok_button": "OK",
    "cancel_button": "Cancel",
    "tooltip_enable_batch_reproject": "Requires a working solver (ASTAP, Astrometry.net, or Ansvr)",
    # final log popup
    "Post-Processing Applied": "Post-Processing Applied",
    "Photutils 2D Background": "Photutils 2D Background",
    "Global Background Neutralization (BN)": "Global Background Neutralization (BN)",
    "Edge/Chroma Correction (CB)": "Edge/Chroma Correction (CB)",
    "Final SCNR": "Final SCNR",
    "Final Edge Crop": "Final Edge Crop",
    "Yes": "Yes",
    "No": "No",
    "Not Found!": "Not Found!",  # Pour le cas où final_stack_path existe mais pas le fichier
    "unaligned_files_message_prefix": "Some images could not be aligned. They can be found in:",
    "open_unaligned_button_text": "Open Unaligned",  # Nouveau bouton
    "unaligned_folder_path_missing": "The path to the unaligned files folder is not defined.",
    "unaligned_folder_not_found": "The unaligned files folder does not exist or is not a directory:",
    "unaligned_folder_opened": "Opening unaligned files folder:",
    "cannot_open_folder_command_not_found": "Could not open folder. System command not found for your OS.",
    "error_opening_unaligned_folder": "An error occurred while trying to open the unaligned files folder:",
    "error_opening_unaligned_folder_short": "Error opening unaligned files folder.",
    "tooltip_drizzle_renorm_disabled": "Flux renormalisation is disabled because the double-normalisation fix is active.",
    # --- Section Feathering ---
    "feathering_frame_title": "Feathering (Weight Map Smoothing)",
    "apply_feathering_label": "Enable Feathering by Weight Map",
    "feather_blur_px_label": "Feather Blur Radius (px):",
    # ---  ---
    # --- Expert Tab - Feathering / Low WHT Mask Section ---
    "feathering_frame_title": "Feathering / Low WHT Mask",  # Title for the combined frame
    "apply_feathering_label": "Enable Feathering (Weighted Smoothing)",  # Existing text, maybe adjust
    "feather_blur_px_label": "Feather Blur (px):",  # Existing text
    "apply_low_wht_mask_label": "Apply Low WHT Mask (Anti-Banding)",
    "low_wht_percentile_label": "Low WHT Percentile:",
    "low_wht_soften_px_label": "Soften Mask (px):",
    "use_best_reference_button": "Use Recommended Reference",
    "status_label": "Status:",
    "apply_snr_rejection": "Apply SNR Rejection",
}
# --- END OF FILE seestar/localization/en.py ---
